---

- name: Check if rustup exists
  shell: "which cargo"
  register: result
  ignore_errors: true

- name: Set facts
  set_fact:
    has_rustup: "{{ result.rc == 0 }}"

- name: See what rust packages are installed
  shell: "cargo install --list"
  register: pkg_check
  when: has_rustup

- name: Download rustup install script
  get_url:
    url: https://static.rust-lang.org/rustup.sh
    dest: /tmp/rustup.sh
  when: not has_rustup

- name: Install rustup
  script: /tmp/rustup.sh
  when: not has_rustup
  become: true

- name: Install cargo packages
  environment:
    RUSTUP_HOME: "{{ data_dir }}/rustup"
    CARGO_HOME: "{{ data_dir }}/cargo"
  shell: "cargo install {{ pkg }}"
  with_items: "{{ rust['pkgs'] }}"
  loop_control:
    loop_var: pkg
  when: pkg not in pkg_check.stdout
