---
- hosts: all
  connection: local
  vars:
    user_name: "{{ lookup('env', 'USER') }}"
    local_home: "{{ lookup('env', 'HOME') }}"
    data_dir: "{{ local_home }}/.local/share"
    anyenv_root: "{{ data_dir }}/anyenv"
    cargo_home: "{{ data_dir }}/cargo"
    rustup_home: "{{ data_dir }}/rustup"
    os_family: "{{ ansible_os_family | lower }}"
  environment:
    GEM_HOME: "{{ data_dir }}/gem"
    RUST_HOME: "{{ rustup_home }}"
    CARGO_HOME: "{{ cargo_home }}"
    PATH: "{{ ansible_env.PATH }}:{{ anyenv_root }}/bin:/opt/homebrew/bin"
    GOPATH: "{{ local_home }}/src/go"
    COURSIER_INSTALL_DIR: "{{ data_dir }}/coursier/bin"
  roles:
    - setup
    - {role: macos, when: ansible_os_family == "Darwin"}
    - {role: debian, when: ansible_os_family == "Debian"}
    - {role: langs}
