---
# Install Homebrew with formulae

# Triggers 'xcode-select --install'
- name: Install homebrew
  shell: 'yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  args:
    creates: /usr/local/bin/brew

- name: Ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes

- name: Enable Homebrew bundle tap
  homebrew_tap:
    name: homebrew/bundle

- name: Check if Brewfile contains updates
  shell: brew bundle check --file="{{ brewfile | default('./Brewfile') }}"
  register: bundle_check_result
  ignore_errors: true

# TODO: Homebrew Cask doesn't handle upgrading already installed applications
#       at /Applications well at all
- name: Install apps using Brewfile
  shell: brew bundle install --file="{{ brewfile | default('./Brewfile') }}"
  when: bundle_check_result is failed

- name: Upgrade all packages
  homebrew:
    upgrade_all: yes

- name: Cleanup
  shell: 'brew cleanup && brew cask cleanup'