---
# Install openvpn profiles

- set_fact:
    target_dir: "{{ data_dir }}/nordvpn"

- name: Create directories
  file:
    path: "{{ target_dir }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    recurse: true

- name: Grab Nordvpn ovpn files
  unarchive:
    src: https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
    dest: "{{ target_dir }}"
    remote_src: true
  args:
    creates: "{{ target_dir }}/ovpn_tcp"

# NB: Add ovpn file to network manager
#     Automatically connect to VPN
#     Use NordVPN DNS servers (v4: 162.242.211.137, v6: ::ffff:162.242.211.137)
#     Constrain to ipv4 to avoid ipv6 leak (ignore ipv6 under network manager settings)
