# Additional package sources to add, and their keys
repositories:
  ppa:
    - "ppa:phoerious/keepassxc"
    - "ppa:marutter/rrutter"
    - "ppa:alexlarsson/flatpak"
    - "ppa:fish-shell/release-2"
    # https://github.com/ChrisRM/material-theme-jetbrains ftw
    # - "ppa:mmk2410/intellij-idea"
    - "ppa:linrunner/tlp"
    # - "ppa:kip/pidgin"
  url:
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable"
    - "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    - "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    # - "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/"
  key:
    - url: "https://download.docker.com/linux/ubuntu/gpg"
      id: 0EBFCD88
    - url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    # - keyserver: "keyserver.ubuntu.com"
    #   id: E084DAB9

# Packages from the default Ubuntu or above sources
packages:
  # base dev tools
  - build-essential
  - apt-transport-https
  - ca-certificates
  - cmake
  - libpq-dev
  - libxml2-dev
  - libxslt1-dev
  - libldap2-dev
  - libsasl2-dev
  - libffi-dev
  - libssl-dev
  - libreadline-dev
  - libncurses5-dev
  - libncursesw5-dev
  # required for PHP
  - libmcrypt-dev
  - libtidy-dev
  # required for R
  - libcurl4-openssl-dev
  - sqlite3
  - libsqlite3-dev
  - libudunits2-dev
  - libgdal-dev
  - libcairo2-dev
  # - redis-server
  # - postgresql
  - postgresql-client
  # cli utilities
  - ncdu # tui to explore disk space usage
  - docker-ce
  - silversearcher-ag
  - bcmwl-kernel-source # kubuntu wifi fix
  - direnv
  - curl
  - icdiff # diff viewer
  - lynx # tui browser
  - gdebi # dependency aware package installer
  - git
  - jq # json processor
  - miller # csv processor
  - symlinks
  - tree # pretty directories
  - vim-gtk
  - xclip
  - zsh
  - tmux
  - neofetch # pretty print system info
  - irssi
  - openvpn
  - net-tools
  - ufw # firewall configuration
  - yank
  - stow
  - gnupg2
  - parallel # GNU parallel
  # - fish
  # - google-cloud-sdk
  # - kubectl
  # - caffeine
  # ruby packages
  - ruby-dev
  # R packages
  - r-base
  - r-base-dev
  - texlive
  - pandoc
  # python packages
  - python-setuptools
  - python3
  - python3-dev
  - python3-pip
  # applications
  - keepassxc # password manager
  - network-manager-openvpn
  # - calibre  # ebook manager; TODO: linux installer script needed!
  # - cheese  # webcam
  # - xournal  # pdf editor
  # - gimp  # image editor
  # TODO: at some point after this, run
  #   flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak # for installing applications
  # - filelight # disk usage analyzer
  # - intellij-idea-community
  # - openjdk-8-jre
  # - zeal  # offline docs viewer
  # for improving battery consumption
  - powertop
  - tlp
  - tlp-rdw
  - pm-utils
  - preload
  - pidgin
  - copyq # clipboard history
  - gnome-subtitles

# Packages to install from remote source, when no PPA is available
remote_packages:
  - "plexmediaserver_1.26.0.5715-8cf78dab3_amd64.deb"
  - "http://kassiopeia.juls.savba.sk/~garabik/software/grc/grc_1.11.3-1_all.deb"
  - "https://github.com/sharkdp/bat/releases/download/v0.3.0/bat-musl_0.3.0_amd64.deb"
  - "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2018.11.28_amd64.deb"
  - "https://prerelease.keybase.io/keybase_amd64.deb"
  - "https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb"
  # - "https://discordapp.com/api/download?platform=linux&format=deb"
  # - "https://download1.rstudio.org/rstudio-xenial-1.1.423-amd64.deb"
  # - "https://downloads.plex.tv/plex-media-server/1.12.0.4829-6de959918/plexmediaserver_1.12.0.4829-6de959918_amd64.deb"
  # - "https://download.virtualbox.org/virtualbox/5.2.8/virtualbox-5.2_5.2.8-121009~Ubuntu~zesty_amd64.deb"

# Remote executables to install
# those that end in tar.gz will be unarchived before being moved to bin
remote_executables:
  - url: "https://github.com/junegunn/fzf-bin/releases/download/0.17.4/fzf-0.17.4-linux_amd64.tgz"
    name: fzf
  - url: "https://github.com/peco/peco/releases/download/v0.5.2/peco_linux_amd64.tar.gz"
    name: peco # interactive cli filtering
  - url: "https://github.com/rgburke/grv/releases/download/v0.1.2/grv_v0.1.2_linux64"
    name: grv # git tui
    # TODO: creates bin64 dir that should be put on path
  #   - url: "https://xpdfreader-dl.s3.amazonaws.com/xpdf-tools-linux-4.00.tar.gz"
  #   - url: "https://github.com/bcicen/ctop/releases/download/v0.7/ctop-0.7-linux-amd64"
  #     name: ctop
  #   - url: "https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64"
  #     name: cloud_sql_proxy
  #   - url: "https://storage.googleapis.com/minikube/releases/v0.25.2/minikube-linux-amd64"
  #     name: minikube
  #   - url: "https://storage.googleapis.com/kubernetes-helm/helm-v2.8.2-linux-amd64.tar.gz"
  #     name: helm
  - url: "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-Linux-x86_64"
    name: docker-compose
  - url: "https://github.com/owenthereal/ccat/releases/download/v1.1.0/linux-amd64-1.1.0.tar.gz"
    name: ccat

flatpaks:
  - us.zoom.Zoom
  - com.valvesoftware.Steam
  - org.signal.Signal
  - com.visualstudio.code

fonts:
  # TODO: rename from e.g. 'Hack Regular Nerd Font Complete' to 'Hack Nerd Font Regular'
  - url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Hack.zip
    name: Hack

snapcraft:
  - universal-ctags
  - emote
